config/routes.rb
Rails.application.routes.draw do

	# REST
	resources :users # RESTのリソースとしてuserの情報を使用する(/users/1)

  get 'sessions/new'
	root 'static_pages#home'
	# この形でルートURLを定義することで、(root)_path,(root)_urlがviewで使用可能
	get '/help',      to: 'static_pages#help'
	get '/about',     to: 'static_pages#about'
	get '/contact',   to: 'static_pages#contact'
	get '/signup',    to: 'users#new'
	post '/signup',   to: 'users#create'
	# session
	get '/login',     to: 'sessions#new'
	post '/login',    to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  # DB格納前に小文字化(メアド一意性対応)
  before_save { self.email = email.downcase } 
  #             email.downcase! メソッド末尾に!で

  # validation定義：presence:true=空を禁止
  validates(:name, presence: true, length: {maximum: 50})

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  # format：正規表現 case_sensitive:false = 大文字・小文字を同一とみなす
  validates(:email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false})
  # passのhash化
  has_secure_password
  validates(:password, presence: true, length: {minimum: 6})

  # 渡された文字列のhashを返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : 
                                                  BCrypt::Engine.cost 
    
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
# 各コントローラーの親となるクラス
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	# session用のhelper読み込み(=全controllerで使用可)
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    # 入力passとhash_passを比較
    if user && user.authenticate(params[:session][:password])
      # ログイン後にユーザーページにリダイレクト
      log_in(user)
      redirect_to user
      # = redirect_to user_url(user)
    else
      flash.now[:danger] = "Invalid email/password conbination" # .now：ページ遷移後、メッセージ削除
      render 'new'
    end
	end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home; end

	def help; end

	def about; end

	def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    @user = User.find(params[:id]) #params[:id] => /users/1 の1?
	end

  # 
  def new
    @user = User.new
  end

  # フォームの入力処理
  def create
    #     = User.new(name: ~~~ , email: ~~~, password: ~~~
    #                password_confirmation: ~~~)
    # @user = User.new(params[:user])
    @user = User.new(user_params)
    if @user.save # 登録成功したら
      log_in(@user) # ログインしとく
      flash[:success] = "Welcome to the sample App!" # redirect先でwelcomeメッセを１回だけ表示
      # 新規userページへリダイレクト
      redirect_to @user # = redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページタイトルが定義されている時はタイトルにbase_titleを付加して返し、
  # タイトルがない場合はbase_titleのみ返す
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	# 受け取ったユーザーでログイン
  def log_in(user)
    # ブラウザのcookieに暗号化ずみのユーザーidを生成
    # cookiesメソッドと違い、sessionメソッドでのcookieはブラウザ終了時に削除される
		session[:user_id] = user.id 
  end

  # login中のユーザーをDBから取り出す(最初の１回だけ)
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])

    #↑と同じ
    # @current_user = @current_user || User.find_by(id: session[:user_id])

    # if @current_user.nil?
    #   @current_user = User.find_by(id: session[:user_id])
    # else
    #   @current_user
    # end
  end

  # loginしていればtrue, していなければfalse
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # grabatarってサービスに画像とかを紐付けるだけのやつ
	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: 'gravatar')
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer"> <small> The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a> by <a href="http://www.michaelhartl.com/">Michael Hartl</a> </small> <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav> </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container"> <%= link_to "sample app", root_path, id: "logo" %> <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b> </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li> <%= link_to "Log out", logout_path, method: :delete %> </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %> </ul>
    </nav> </div>
</header>

app/views/layouts/_rails_default.erb
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim'%>
</head>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/rails_default' %>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%#  show temporaly message %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%# show body %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%# show debug info %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any?  %> <%# any?: <=> empty? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li> <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About</h1>
<p> <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href="https://railstutorial.jp/#ebook">book</a>
  and <a href="https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial. 
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<h1>Help</h1>
<p> Get help on the Ruby on Rails Tutorial at the 
  <a href="https://railstutorial.jp/help">
    Rails Tutorial help page</a>. 
  To get help on this sample app, see the 
  <a href="https://railstutorial.jp/#ebook">
    <em>Ruby on Rails Tutorial</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2> This is the home page for the 
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a> sample application. 
  </h2>
  <%= link_to "Sign up now!", 'signup_path', class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag("rails.png", alt:"Rails logo"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, "Sign up")%>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%# use helper method: form_for %>
    <%= form_for(@user, url: signup_path) do |f| %>
      <%# show error_message from shared/error_messages %>
      <%= render 'shared/error_messages' %>
      <%# name %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%# email %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      <%# pass %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%#  %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%# use gravatar_image %>
        <%= gravatar_for(@user) %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>